name: Daily LeetCode Sync

on:
  schedule:
    - cron: "30 2 * * *"   # runs daily at 8:00 AM IST
  workflow_dispatch:       # lets you run manually too

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run LeetCode sync
        env:
          env:
  LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_NAME: ${{ secrets.REPO_NAME }}
  LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}

        run: python leetcode_to_github.py
