name: Daily LeetCode Sync

on:
  schedule:
    - cron: "30 2 * * *"   # Runs daily at 8:00 AM IST
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Set Git identity
        run: |
          git config --global user.name "Shreyas Kamat"
          git config --global user.email "192124395+ShreyasNK2006@users.noreply.github.com"

      - name: Run LeetCode Sync
        env:
          LEETCODE_USERNAME: ${{ secrets.LEETCODE_USERNAME }}
          LEETCODE_SESSION: ${{ secrets.LEETCODE_SESSION }}
          REPO_NAME: ${{ secrets.REPO_NAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: python leetcode_to_github.py

      - name: Commit and Push Changes
        run: |
          git add .
          git commit -m "Daily LeetCode Sync" --author="Shreyas Kamat <192124395+ShreyasNK2006@users.noreply.github.com>" || echo "No changes to commit"
          git push origin main
